import type { Metadata } from "next";
import { IBM_Plex_Sans, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

const plexMono = IBM_Plex_Mono({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

const plexSans = IBM_Plex_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hello, Worlds!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${plexSans} ${plexMono} antialiased text-neutral-700 dark:text-neutral-200 bg-white dark:bg-black font-sans`}
      >
        <ThemeProvider enableSystem={true} defaultTheme="system">
          <Nav />
          <main className="min-h-screen container">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
